
server:
  port: 8080


  # Database config
spring:
  datasource:
    url: jdbc:h2:file:/Users/a865282/Documents/workspaces/spring-boot-ssl/App
    driverClassName: org.h2.Driver
    username: test
    password: test
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console.enabled: true

